### ISSUE TITLE
Images in navigation menu are not shown outside of development mode

### ISSUE THREAD

**Issue by djowett** [4teamwork/ftw.mobilenavigation#31]
I believe this is because you need applyPrefix="True" when registering the CSS, but I need to test this.

```xml
  <stylesheet id="++resource++ftw.mobilenavigation/navigation.css"
              media=""
              enabled="True"
              applyPrefix="True"
              />
```

**Comment by jone** [comment]
Yes, I think that is true, and the fix should work.

@Tschanzt can you take care of that and change it with an upgrade step?

**Comment by djowett** [comment]
Thanks, I can confirm it does fix it when I (re)apply it in my policy product.
